### ISSUE TITLE
Can compat layer be changed to account for serverless-plugin-warmup

### ISSUE THREAD

**Issue by barrysteyn** [danielcondemarin/serverless-nextjs-plugin#108]
I am wondering if the compat layer can be altered to account for *serverless-plugin-warmup*. The plugin calls all one's lambdas on a scheduled bases. It sets the event.source to *serverless-plugin-warmup*, and so all the compat layer would need to do is check for this and exit if it sees it.

Perhaps this can even be taken care of in a custom handler, but it would be more simple to just let the compat layer account for it. Am I missing something?

**Comment by danielcondemarin** [comment]
Hi @barrysteyn this sounds like something you should be able to achieve with a custom handler, i.e.:

```js
const compat = require("next-aws-lambda");

module.exports = page => {
  const handler = (event, context, callback) => {
   if (event.source === 'serverless-plugin-warmup') {
      return callback(null, 'Lambda is warm!')
   }

    // otherwise render page
    compat(page)(event, context, callback);
  };

  return handler;
};
```

Feel free to reopen if you find any issues with this approach.
