### ISSUE TITLE
serverless-sentry & serverless-nextjs-plugin

### ISSUE THREAD

**Issue by romainquellec** [danielcondemarin/serverless-nextjs-plugin#12]
Is serverless-nextjs-plugin compatible with serverless-sentry ?
If not, how can we modify handlers to add the sentry layer.

(Sorry for the spam with issues 🙃)

**Comment by danielcondemarin** [comment]
> (Sorry for the spam with issues 🙃)
You're keeping me very busy! haha. 

From the top of my head, I can't see why it wouldn't be compatible. I would put the serverless-nextjs-plugin first in the list:

```yml
plugins:
  - serverless-nextjs-plugin
  - serverless-sentry
```

**Comment by romainquellec** [comment]
The sentry plugin require to add a layer around the lambda, so I guess, we need to do that for each handlers :

```
const Raven = require("raven"); // Official `raven` module
const RavenLambdaWrapper = require("serverless-sentry-lib"); // This helper library

exports.handler = RavenLambdaWrapper.handler(Raven, async (event, context) => {
  // Here follows your original Lambda handler code...
  return { message: 'Go Serverless! Your function executed successfully!', event };
});
```

**Comment by mekwall** [comment]
This is more about adding support for custom handlers since that will automatically support Sentry and any other library that requires you to wrap your handlers. I very much look forward to that feature myself because I am looking at adding cache to a server-side rendered React app and I need to be able to wrap with my own handler to do that.

I might be able to contribute to make it happen but need to sync with @danielcondemarin on the design of the API.

**Comment by danielcondemarin** [comment]
@mekwall Would be great if you can contribute to this 🙏 

Here is a proposed API, let me know your thoughts:

```yml
// serverless.yml

custom:
  serverless-nextjs:
   customHandler: /path/to/handler.js
```

The plugin still is responsible for the finalised handler that the page lambda uses:

### When `customHandler` is provided

```js
// Plugin handler (see lib/getCompatLayerCode.js)

const page = require("${PAGE_BUNDLE_PATH}");
const handlerFactory = require("${CUSTOM_HANDLER_PATH}"); // CUSTOM_HANDLER_PATH === /path/to/handler.js

module.exports.render = (event, context, callback) => {
  const handler = handlerFactory(page);
  handler(event, context, callback);
};
```

```js
// /path/to/handler.js

const compat = require('serverless-nextjs-plugin/aws-lambda-compat');

module.exports = ({ page }) => {
  const handler = (event, context, callback) => {
    // do any stuff you like

    // make sure the next page renders etc.
    compat(page)(event, context, callback);

    // do any other stuff you like
  };

  return handler;
};
```

For example, `serverless-sentry` handler might look like:

```js
// custom sentry handler

const compat = require('serverless-nextjs-plugin/aws-lambda-compat');

module.exports = ({ page }) => {
  return RavenLambdaWrapper.handler(Raven, (event, context, callback) => {
      // Here follows your original Lambda handler code...
      compat(page)(event, context, callback);
  })
};
```

Or `AWS-X-Ray`:

```js
// custom aws-x-ray handler

const compat = require('serverless-nextjs-plugin/aws-lambda-compat');
import AWSXRay from 'aws-xray-sdk-core'

AWSXRay.enableManualMode();

module.exports = ({ page }) => {
  const handler = (event, context, callback) => {
    const segment = new AWSXRay.Segment('hello')

    try {
      compat(page)(event, context, callback);
    } catch(err) {
      segment.addError(err)
    } finally {
      segment.close()
    }
  }

  return handler;
};
```

### When `customHandler` isn't provided

No different from what currently happens, simply render the next page

```js
// Plugin handler (see lib/getCompatLayerCode.js)
const page = require("${PAGE_BUNDLE_PATH}");
const compat = require('serverless-nextjs-plugin/aws-lambda-compat')(page);

module.exports.render = (event, context, callback) => {
  compat(event, context, callback);
};
```

`serverless-nextjs-plugin/aws-lambda-compat` doesn't actually exist yet, it would be `lib/compatLayer.js` basically.

Hope that makes sense and if you have any questions, please fire away

Cheers

**Comment by mekwall** [comment]
@danielcondemarin I like it! Will open a PR soon for review.
