### ISSUE TITLE
Unable to reuse db connections in API due to a non-empty event loop

### ISSUE THREAD

**Issue by Deadleg** [danielcondemarin/serverless-nextjs-plugin#125]
As documented here https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html, for non-async lambdas which is what this plugin creates the lambda terminates only when the event loop is empty.

An example is to create a connection with `mysql` and keep the connection open for the next invocation to reduce the overhead of creating new connections. The lambda will continue to run after called `res.end` leading to timeouts.

I can see two likely solutions to this:

1. Refactor the entry point to be an async function.
2. Set `context.callbackWaitsForEmptyEventLoop = false` by default in the entry point.

Option 2. seems to be pretty easy, but I'm not sure if there are any other side effects compared to using `async`. We could also just set it for APIs since that's the only place were I image people would need it.

**Comment by danielcondemarin** [comment]
@Deadleg thanks for the awesome contributions in the last couple of days! I would be very interested in making the entry point async! It should be relatively straightforward to do that. Feel free to PR if you got time.

**Comment by danielcondemarin** [comment]
In fact, I've found today making it async might not be a great idea after all. 

From https://docs.aws.amazon.com/lambda/latest/dg/limits.html:
![image](https://user-images.githubusercontent.com/1122442/63447466-f9830400-c433-11e9-9aa6-67e0c3ad06ae.png)

That would limit the response size significantly.

**Comment by danielcondemarin** [comment]
I've refactored the compat layer to support the async signature. It also maintains backward compat with the `callback` approach. @Deadleg I've not tested it, but this issue should be fixed in the new release. Feel free to reopen if you encounter any problems.
