### ISSUE TITLE
a way to remove the suffix /dev from deployments?

### ISSUE THREAD

**Issue by johhansantana** [danielcondemarin/serverless-nextjs-plugin#126]
I'm having trouble testing and serving static files since it's trying to look into `/static/...` but since the lambda functions are listening to `/dev/static/...` I would need to change them in my code to point there.

Is there a way to remove the suffix `/dev` from deployments? I've tried changing stages but still no good.

**Comment by danielcondemarin** [comment]
You will need a custom api gateway domain name to get rid of the stage. More info on how to do that here: https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-custom-domains.html. Alternatively setup a [CloudFront distribution](https://github.com/danielcondemarin/serverless-nextjs-plugin#serving-static-assets) and configure a domain for it.
