### ISSUE TITLE
Files in buckets on Windows

### ISSUE THREAD

**Issue by romainquellec** [danielcondemarin/serverless-nextjs-plugin#18]
For local testing, I'm using windows.
The files in the bucket for the assets seems broken : 
![image](https://user-images.githubusercontent.com/1150703/54695976-408a6780-4b2b-11e9-9968-e93f41ca50a1.png)

I will try with CircleCI, but it seems that Windows env. doesnt like the filenames.

**Comment by romainquellec** [comment]
Its definitelyrelated to Windows. It's working like a charm on CircleCI

**Comment by danielcondemarin** [comment]
I've not tested the plugin in Windows at all. I would happily accept a PR with any fixes for Windows.

**Comment by romainquellec** [comment]
I'm using CircleCI a lot, but I can improve Windows support. 👍

**Comment by danielcondemarin** [comment]
Now v1.5 supports Windows 🎉
