### ISSUE TITLE
Issue with Lambda : path not correct

### ISSUE THREAD

**Issue by romainquellec** [danielcondemarin/serverless-nextjs-plugin#19]
Deployment on Windows :

![image](https://user-images.githubusercontent.com/1150703/54700254-eee5db00-4b32-11e9-9a1b-16fb30762a80.png)

The path generated is sls-next-build\account.render, it should be : 
sls-next-build/account.render

**Comment by romainquellec** [comment]
When fixed, I've got this on compatLayer : l14
```
2019-03-20T16:21:08.487Z	7fec656c-7ad5-40fd-ad34-ccebdb21a085	TypeError: Cannot read property 'path' of undefined
    at reqResMapper (/var/task/sls-next-build/compatLayer.js:14:35)
    at module.exports.render (/var/task/sls-next-build/account.js:6:24)
```

CompatLayer l14
```
  req.url = (event.requestContext.path || event.path || "").replace(
    new RegExp("^/" + event.requestContext.stage),
    ""
  );
```

**Comment by romainquellec** [comment]
FYI, this is when I test like that :

![image](https://user-images.githubusercontent.com/1150703/54701486-63ba1480-4b35-11e9-8335-65cf77d123b5.png)

**Comment by danielcondemarin** [comment]
@romainquellec I've added support for windows on v1.5.0 👍
