### ISSUE TITLE
CORS with bucket 

### ISSUE THREAD

**Issue by romainquellec** [danielcondemarin/serverless-nextjs-plugin#20]
Loading assets with bucket is broken on last Chrome :
see : https://www.chromestatus.com/feature/5629709824032768 

![image](https://user-images.githubusercontent.com/1150703/54747257-b1369000-4bce-11e9-94a0-56b52fcce879.png)

**Comment by romainquellec** [comment]
Maybe related to the url of bucket : 
https://s3-eu-west-1.amazonaws.com/ ... works
https://s3.amazonaws.com/ doesnt

**Comment by romainquellec** [comment]
So yes, bucket must contain region.

**Comment by romainquellec** [comment]
As you know, I'm not very happy with the bucket solution right now.
Do you know if this is possible to upload assets in another bucket not related to the ssr stack ?

If so, this asset can be created in Route53, CloudFront, and get a real url like assets.EXAMPLE_Domain.com.

**Comment by romainquellec** [comment]
Another way I can think of is adding a layer in index.js handling static file as express do it.
Something similar as 
```
app.use("/_next/static", express.static(path.join(__dirname, "/static")));
```

**Comment by danielcondemarin** [comment]
> As you know, I'm not very happy with the bucket solution right now.
> Do you know if this is possible to upload assets in another bucket not related to the ssr stack ?
> 
> If so, this asset can be created in Route53, CloudFront, and get a real url like assets.EXAMPLE_Domain.com.

You should be able to do this now by using the plugin config `assetsBucketName`  😀 https://github.com/danielcondemarin/serverless-nextjs-plugin#hosting-static-assets

**Comment by romainquellec** [comment]
👍

**Comment by romainquellec** [comment]
Closing this for : https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/31
