### ISSUE TITLE
feat: deploy static files in the static directory to s3

### ISSUE THREAD

**Issue by bushmango** [danielcondemarin/serverless-nextjs-plugin#29]
The next static files deploy correctly, but the files in the special next directory /static don't get copied to either aws or to the s3 bucket.

It would be nice to also copy /static/** to the s3 bucket

**Comment by Jole83** [comment]
You can use serverless-s3-sync for that.

**Comment by sja** [comment]
Hmm, I cannot see that feature on `serverless-s3-sync`. Only caching headers are supported. Where do you have that info from?

**Comment by Jole83** [comment]
You can use it like this e.g :
plugins:
  - serverless-nextjs-plugin
  - serverless-offline
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: static-files
      bucketPrefix: assets/ # this is prefix that you can set so it doesn't override if you use same bucket like in assetPrefix
      localDir: static # this is local directory where your static files are
      acl: public-read # optional

**Comment by sja** [comment]
I'm sorry, I had my ticket in mind #28 which is about gzipped upload.

**Comment by danielcondemarin** [comment]
Hi folks, just released v1.6.0 which adds supports for a new staticDir option, you can now point to a directory and will be uploaded to the bucket for you. More details here: https://github.com/danielcondemarin/serverless-nextjs-plugin#hosting-static-assets
