### ISSUE TITLE
Multiple react versions killing hooks

### ISSUE THREAD

**Issue by bushmango** [danielcondemarin/serverless-nextjs-plugin#32]
With npm ls react, I get two different versions:

cowsayify-v3@3.0.0 /home/sbushman/dev/cowsayify-v3/client
├── react@16.8.6 
└─┬ serverless-nextjs-plugin@1.5.0
     └── react@16.8.4 

I think serverless-nextjs-plugin should have a peer dependency instead of a direct dependency to react.

I get a hook error when deploying that I have mismatched react version

**Comment by danielcondemarin** [comment]
You’re right. Happy to accept a PR for that 😁 otherwise I’ll look at it later this week

**Comment by bushmango** [comment]
Opened: https://github.com/danielcondemarin/serverless-nextjs-plugin/pull/37

**Comment by danielcondemarin** [comment]
This should now be fixed in https://github.com/danielcondemarin/serverless-nextjs-plugin/releases/tag/v1.5.1 🎉
