### ISSUE TITLE
CodeSandBox example

### ISSUE THREAD

**Issue by romainquellec** [danielcondemarin/serverless-nextjs-plugin#36]
I'm trying to create a sandbox for a bug with next-seo with serverless.
I don't know if there is a starter point, but I tried this :
https://codesandbox.io/embed/l2n6mq54p7

If someone is good with Codesandbox, maybe it can help beginners.

**Comment by danielcondemarin** [comment]
@romainquellec Just forked your sandbox https://codesandbox.io/s/3qpvmj7r91 and seems to work. Not entirely sure but your version of `serverless-offline` might have been outdated. Try reinstalling and restart the sandbox

**Comment by romainquellec** [comment]
Thanks ! The sandbox is working like a charm. Maybe, you should link it the readme ?

**Comment by danielcondemarin** [comment]
I’ll look at polishing it a bit more and add it later 👍🏻
