### ISSUE TITLE
Serverless deploy fails due to an existing s3 bucket

### ISSUE THREAD

**Issue by jonathanwelton** [danielcondemarin/serverless-nextjs-plugin#45]
After the initial deploy, subsequent deploys fail since the assets S3 bucket already exists.

Is there any extra configuration required in my Serverless .yml file to make Cloud Formation aware of the bucket state?

**Comment by danielcondemarin** [comment]
Sounds like you are trying to provision 2 different stacks with the same bucket name. 
The bucket is only created on the initial deploy of the serverless stack, you shouldn't need any extra configuration. Can you provide a repro?

**Comment by jonathanwelton** [comment]
Sorry it's not in a public repo...but I can include the configuration files below (with the application name replaced):

**serverless.yml**
`service: application

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'test'}
  region: eu-west-1
  memorySize: 128
  logRetentionInDays: 1
  timeout: 10

plugins:
  - serverless-nextjs-plugin

custom:
  serverless-nextjs:
    nextConfigDir: "./"
    assetsBucketName: "${self:provider.stage}-application"

package:
  exclude:
    - ./**`

**next.config.js**
`const withSass = require('@zeit/next-sass')

const config = {
  assetPrefix: `https://${process.env.stage}-application.s3-eu-west-1.amazonaws.com`,
  target: "serverless",
  exportPathMap: async function (defaultPathMap) {
    return {
      '/': { page: '/' },
      '/about': { page: '/about' }
    }
  },
  env: {
    release_api_url: process.env.api_url,
    release_api_key: process.env.api_key
  }
}

module.exports = withSass(config);
`

**Comment by danielcondemarin** [comment]
You don't need `assetsBucketName: "${self:provider.stage}-application"` in the `serverless.yml`. The plugin will see that your `assetPrefix` is an amazon s3 url and will provision with the correct name. 
Not sure if that fixes the problem but is a good start :-)

**Comment by sja** [comment]
I've the same. My `assetsBucketName` is `${self:provider.stage}-app` because my `assetPrefix` is `https://static.staging.app.com`, which is a cloudformation distibution.

**Comment by sja** [comment]
I think my situation was that I worked with 1.5.2 where s3 upload did not work, now changed to 1.5.3 and some S3 operations were added which confuses the handling.

So to start (at S3) from beginning, I deleted the bucket and again started a deployment. Now I get that error:

```
Bad Request (Service: Amazon S3; Status Code: 400; Error Code: 400 Bad Request; Request ID: 733766BE01E46A5C; S3 Extended Request ID: PlGfLqZzviikn3YN3LwHlTulccktunRbN3b6A+d7TL4w8/2qubSPMd2Nsa6+i/SwSZaGMaPFeTY=)
```

The Template is:
```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "The AWS CloudFormation template for this Serverless application",
  "Resources": {
    "ServerlessDeploymentBucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "BucketEncryption": {
          "ServerSideEncryptionConfiguration": [
            {
              "ServerSideEncryptionByDefault": {
                "SSEAlgorithm": "AES256"
              }
            }
          ]
        }
      }
    },
    "NextStaticAssetsS3Bucket": {
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "AccessControl": "PublicRead",
        "CorsConfiguration": {
          "CorsRules": [
            {
              "AllowedHeaders": [
                "*"
              ],
              "AllowedMethods": [
                "GET"
              ],
              "AllowedOrigins": [
                "*"
              ],
              "ExposedHeaders": [
                "Date"
              ],
              "Id": "NextStaticAssetsS3BucketId1",
              "MaxAge": "3600"
            }
          ]
        },
        "BucketName": "staging-app",
        "WebsiteConfiguration": {
          "IndexDocument": "index.html",
          "ErrorDocument": "error.html"
        }
      },
      "DeletionPolicy": "Retain"
    }
  },
  "Outputs": {
    "ServerlessDeploymentBucketName": {
      "Value": {
        "Ref": "ServerlessDeploymentBucket"
      }
    },
    "NextStaticAssetsS3BucketWebsiteURL": {
      "Value": {
        "Fn::GetAtt": [
          "NextStaticAssetsS3Bucket",
          "WebsiteURL"
        ]
      },
      "Description": "URL for the S3 website hosting the static assets"
    },
    "NextStaticAssetsS3BucketSecureURL": {
      "Value": {
        "Fn::Join": [
          "",
          [
            "https://",
            {
              "Fn::GetAtt": [
                "NextStaticAssetsS3Bucket",
                "DomainName"
              ]
            }
          ]
        ]
      },
      "Description": "S3 Bucket which holds the static assets"
    }
  }
}
```

**Comment by danielcondemarin** [comment]
@sja the bucket has to be created as part of the initial deployment of the serverless stack. You can't delete the bucket and rely on it being created again for you on update. It only works the first time you run `serverless deploy` when the stack is created for the first time.

**Comment by kjvenky** [comment]
Can the documentation be improved on this? I am facing similar issue and no clue why it keeps happening.

**Comment by danielcondemarin** [comment]
@kjvenky I’m planning to add some validation that checks if the bucket has been deleted after the initial stack creation. I believe serverless does the same for the ServerlessDeploymentBucket. I’ll also update the docs 👍🏻

**Comment by mattdell** [comment]
Or at least delete the S3 bucket as part of the `serverless remove` command.

I run into this if I need to remove a development stack and then try to deploy it again.

**Comment by KylePalko** [comment]
To get this to work I had to create the S3 bucket with Serverless first:

```
resources:
  Resources:
    NextStaticAssetsS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ***BUCKET_NAME***
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
```

Before I could deploy this I had to comment out `assetsBucketName: '***BUCKET_NAME***'` in the `Serverless.yml` file and `assetPrefix: 'https://s3.amazonaws.com/***BUCKET_NAME***'`in the `next.config.js` file.

After I successfully deployed the S3 bucket using Serverless I uncommented the lines above and deployed again. This resolved the issue for me.

**Comment by danielcondemarin** [comment]
Hi folks, can you try [v1.8.0](https://github.com/danielcondemarin/serverless-nextjs-plugin/releases/tag/v1.8.0) and let me know if this is still an issue? I did a few changes to how the S3 bucket is provisioned that might have fixed this.

**Comment by Prefinem** [comment]
Still getting an error.

Using an already created bucket

```bash
...
Serverless: Operation failed!
Serverless: View the full error output: https://us-east-1.console.aws.amazon.com/cloudformation/home?region=us-east-1#/.....
 
Serverless Error ---------------------------------------

An error occurred: NextStaticAssetsS3Bucket - assets.example.com already exists.
```

Using a new bucket (non-existant)
```
Serverless Nextjs: Uploading .next/static to asset.example.com ...
 
Serverless Error ---------------------------------------
 
The specified bucket does not exist
```

next.config.js file
```js
module.exports = () => ({
	assetPrefix: 'https://assets.example.com',
	target: 'serverless',
});
```

serverless.yml
```yml
custom:
  serverless-nextjs:
    nextConfigDir: './'
    assetsBucketName: 'asset.example.com'
```

**Comment by Prefinem** [comment]
For the existing bucket, it looks like you upload and then still add the bucket to the CloudFormation resources. (this might not be a feature though)

It looks like for non existant s3 buckets, the upload of assets is happening before the CloudFormation is finished creating all the resources.

**Comment by Prefinem** [comment]
Just tested with a different hook for `this.uploadStaticAssets` and didn't have any issues

```js
"after:aws:deploy:finalize:cleanup": this.uploadStaticAssets,
```

**Comment by danielcondemarin** [comment]
I think this issue arises from lack of documentation of how the assets bucket provisioning works, so let me clarify:
- You should let the assets bucket creation to the plugin. It does this via CF.
- If you delete the assets bucket manually, you'll have to recreate it manually, don't expect the plugin to do this for you. It can only create it the first time the stack is provisioned.
- If you have 2 serverless stacks under the same AWS Account, make sure you have 2 different asset buckets, you can't reuse the same for 2 serverless apps, i.e. different environments.

I've also added validation on https://github.com/danielcondemarin/serverless-nextjs-plugin/pull/83 that should help towards making this clearer.
