### ISSUE TITLE
Question about multiple Lambda code bundles and cold boot times

### ISSUE THREAD

**Issue by willbamford** [danielcondemarin/serverless-nextjs-plugin#48]
At the moment this plugin creates a single code bundle with all of the handler functions as separate files within e.g. `my-app.zip` with `homepage.js` and `product.js` in the zip.

However, I thought one of the main reasons that Next.js created a Lambda per function was so that Lambda code bundle size could be kept to a minimum thus improving cold boot times? I.e. might have expected `my-app-homepage.zip`, `my-app-product.zip` etc. instead?

**Comment by danielcondemarin** [comment]
The lambda, at runtime **only requires** a single page bundle, regardless of what's inside the deployment artifact. I think this is what makes most of the difference compared to the more traditional monolith approach which at runtime serves all the pages.
However, you're right there could be separate deployment artifacts per Lambda each with the separate page bundles, which in theory should improve the time involved in downloading the artifact from the Lambda.
I'm going to close this in favour of a feature request 
https://github.com/danielcondemarin/serverless-nextjs-plugin/issues/49.
Thanks!

**Comment by willbamford** [comment]
Yes, I saw that only a single require was used per page - I can see how this should have a big impact. Instinctively it feels like the size of each bundle should also affect cold start but interestingly this article suggests that it does not https://read.acloud.guru/does-coding-language-memory-or-package-size-affect-cold-starts-of-aws-lambda-a15e26d12c76

Thanks for raising the feature 👍

**Comment by danielcondemarin** [comment]
Yeah read the same article! I do however feel like the individual artefacts make more sense, especially considering it's easy to implement and shouldn't affect anything else, so will have a look when I get a chance 👍

**Comment by willbamford** [comment]
BTW - just to follow up on this. Bundle size did indeed make a difference to cold start times when I tested this:

<img width="494" alt="Screen Shot 2019-05-15 at 20 12 06" src="https://user-images.githubusercontent.com/357579/57802401-c0a90400-774d-11e9-9038-ac4983f54d69.png">

**Comment by danielcondemarin** [comment]
How do you know is bundle size and not the overhead added by express?  I expect the bootstrap times for express to be higher.

**Comment by willbamford** [comment]
Yeah that's fair but I think that should be reflected in the difference in hot start time I.e. slower by ms not seconds. I  will try large single page bundle to verify though.

**Comment by willbamford** [comment]
Okay you're right - it does look like Express cold boot is what accounts for most of the slowdown:

<img width="606" alt="Screen Shot 2019-05-16 at 07 01 53" src="https://user-images.githubusercontent.com/357579/57830002-a3edea00-77a8-11e9-84ce-677200b76bbe.png">

Bundle size does still seem to make a small difference - but I was only able to do a quick experiment (5 cold + 5 hot starts in each env).

**Comment by willbamford** [comment]
@danielcondemarin I'm starting to wonder whether it actually might be better to keep a single bundle? Also, now not sure what benefits of Next.js "serverless" approach is i.e. self-contained page-level JS files. I can only imagine is slows down builds (imagine 50x page-level JS files, each of which has same dependencies baked in e.g. React), means more Lambdas to manage (using Terraform / Serverless etc. - and potential CloudFormation resource limit issues from latter) vs. just having single bundle, single Lambda + v. lightweight routing (not Express).

**Comment by danielcondemarin** [comment]
Next serverless approach means horizontally scalable pages. For example, doesn't matter how much your bundle size grows you'll never hit a Lambda size limit. The same applies to the Lamba memory, with one lambda for everything you can only scale that vertically.

The management aspect you could argue that serverless is doing that for you. I would ask what is it difficult to manage?

In terms of the CF limits you're absolutely right, that's an issue. At some point I hope Amazon increases the limit or serverless introduces some workaround for it but seems like that might take a while.

**Comment by willbamford** [comment]
Yeah, I want to believe in the above but I can't imagine practically hitting bundle size limits for lambda with single app (at least for projects I'm thinking of).

I'm terms of scaling only certain pages over others I'm not really sure how this results in better performance tbh (can't imagine it really affects number of cold boots).

This plugin is great for managing deployment (although it may not be an option for us).

I think there are some arguments about isolation and with that better security and perhaps the potential to deploy only changed Lambdas? The speed improvements at the moment may come from having single code by bundle vs. requiring into node_modules.

Anyway, thanks for your time - I should take this question to the Next.js forum.

**Comment by danielcondemarin** [comment]
@willbamford Thought to let you know about the new [next component](https://github.com/danielcondemarin/serverless-next.js/tree/master/packages/serverless-nextjs-component) release. I believe it addresses some of your concerns above :)
