### ISSUE TITLE
static `getInitialProps` triggers page flash

### ISSUE THREAD

**Issue by vgrafe** [danielcondemarin/serverless-nextjs-plugin#5]
When debugging locally, using `getInitialProps` to provide initial props to a page, the client side app seems to not get anything out of it. When reloading a page, the desired props will be passed to render, then shortly after the page will render as if no props were set.

A console error will be output in the browser : "Warning: Text content did not match."

**Comment by danielcondemarin** [comment]
Hi @vgrafe Can you provide an example where this can be reproduced? I tried something really basic like this and seems to work fine:

```
class SayHi extends React.Component {
  static async getInitialProps({ query }) {
    return {
      name: query.name
    };
  }

  render() {
    return <span>{`hi there ${this.props.name}`}</span>;
  }
}
```
// http://localhost:3000/about?name=batman

**Comment by vgrafe** [comment]
Ok, I found the cause of the bug. I might be doing something wrong when adding `@zeit/next-typescript`. 

I know it is not related to your plugin but I'll leave steps to repro here to explain:
1- `npm i @zeit/next-typescript --save`
2- change `next.config.js` to the following:
```js
const withCSS = require("@zeit/next-css");
const withTypescript = require('@zeit/next-typescript');

module.exports = withTypescript(
  withCSS({
    assetPrefix: 'https://s3.amazonaws.com/example_bucket'
  })
);
```
3- `npm run dev`

You'll observe the flash described initially. I might be missing on something when adding ts to my codebase.

No hard feelings if you close, now I'll look closer in the nextjs/ts docs.

**Comment by vgrafe** [comment]
Alright, for whoever runs into that, here's the correct code for the config file: 

```js
const withCSS = require("@zeit/next-css");
const withTypescript = require('@zeit/next-typescript');

module.exports = 
  withCSS(withTypescript(), {
    assetPrefix: 'https://s3.amazonaws.com/example'
  });
```

**Comment by vgrafe** [comment]
Apologies. This solves TS but breaks CSS.

**Comment by danielcondemarin** [comment]
@vgrafe How does it break CSS?

**Comment by vgrafe** [comment]
With that config, CSS is not loaded when navigating to a page through a next `Link`. 
But once on such a page, reloading the browser refreshed the page with styles. Navigating away then back show that the styles are still loaded.

**Comment by vgrafe** [comment]
[Here is a repo for better illustration.](https://github.com/vgrafe/nbi)

I found out the right way to combine plugins, but CSS loading still has some issues: the `import` statement loading the css file does not seem to work when the page is navigated to. As soon as the page is loaded directly (or reloaded), the css is applied for the remaining lifetime of the webapp.

**Comment by danielcondemarin** [comment]
@vgrafe Unfortunately I don't think the Next Links will work properly with API gateway stages in the base path, e.g. https://kw0e2oks0a.execute-api.us-east-1.amazonaws.com/dev/about, https://kw0e2oks0a.execute-api.us-east-1.amazonaws.com/dev/. 
There is an open Feature Request in next to support this: https://github.com/zeit/next.js/issues/4998.
I'm looking into workarounds but for now you could try using a custom domain for your API GW and that should work fine with next links.

**Comment by vgrafe** [comment]
Sorry I was not clear - the issue happens when working locally, with `yarn dev`/`npm run dev`. I am aware of the problem with the api basepath, which is only resolved if mapped to a domain at this time.

**Comment by danielcondemarin** [comment]
In that case you will be better off raising the issue in the nextjs repo. When you run yarn dev in your example the plugin is not doing anything, instead just a normal next build happens. The plugin kicks in only when you run serverless deploy or serverless package commands.

**Comment by vgrafe** [comment]
Sounds good! Thank you for your help.
