### ISSUE TITLE
Custom handler isn't build

### ISSUE THREAD

**Issue by romainquellec** [danielcondemarin/serverless-nextjs-plugin#61]
When you add a custom handler like this : 
```
const compat = require("serverless-nextjs-plugin/aws-lambda-compat");
const Raven = require("raven");
const RavenLambdaWrapper = require("serverless-sentry-lib")

module.exports = page => {
    return RavenLambdaWrapper.handler(Raven, (event, context, callback) => {
        compat(page)(event, context, callback);
    })
};
```
After build phase, the handler isnt transform as pages are. I think this should be the custom behavior.

Alternative : add the custom packages in the final artifact, but I think first option is the best.

**Comment by danielcondemarin** [comment]
Hi @romainquellec, not sure what do you mean by transformed?  The custom handler is included in the deployment zip artifact.

**Comment by mekwall** [comment]
I think I understand what he means, that `raven` and `serverless-sentry-lib` aren't added to the bundle automatically.

You need to ensure that `raven` and `serverless-sentry-lib` packages and their dependencies are included in your package by adding them to your (not) exclude.

My config looks like this:
```
package:
  excludeDevDependencies: false
  exclude:
    - './**'
    - '!node_modules/**'
```
Note that I'm using a monorepo and most packages are hoisted to the root. Only the packages I want to include are not hoisted. It's a nifty way not having to specify every single package manually.

**Comment by romainquellec** [comment]
@mekwall Exactly that. :D

**Comment by mekwall** [comment]
Another solution is to create a sub-package inside your package, that only has `raven` and `serverless-sentry-lib` in its `package.json` and then add the node_modules directory from that package to your (not) exclude.

**Comment by danielcondemarin** [comment]
@romainquellec Did any of the solutions above worked for you? Including the node_modules you need as @mekwall suggested sounds sensible. 
Automatically including dependencies of the custom handler I think goes beyond the scope of the plugin.

**Comment by romainquellec** [comment]
I didnt try.
Imo, The handle should be treated as pages are. There are no reason the handle shouldnt be optimized  with webpack.

(Also, sometimes, when you include a package with serverless (as @mekwall suggested), the other packages needed for the included package arent automatically included)

**Comment by mekwall** [comment]
@romainquellec If you create a sub-package, with its own package.json you just run `npm install` in the sub-package and then include the node_modules from the sub-package in your serverless config. That way you get all of the dependencies you need.

And I kind of agree with @danielcondemarin that this might be out of scope for this plugin to bundle all of it. Maybe if there's a way to hook into Next.js build process in some way, but having two different build processes feels wrong.

**Comment by danielcondemarin** [comment]
Closing as there are possible workarounds for this and building the handlers should be done outside the plugin
