### ISSUE TITLE
Deployments in a monorepo setup include entire path in s3 bucket

### ISSUE THREAD

**Issue by me4502** [danielcondemarin/serverless-nextjs-plugin#75]
I've got a NextJS project in a monorepo setup, and when being deployed with this plugin it places the assets in the full path from the root of the git repo/yarn workspaces setup (Including the parent folder?).

Due to this, when visiting the page it cannot find the bundle. It's looking in S3/_next/static, whereas it is actually in S3/_next/parent folder/apps/project name/.next/static

Is there a way to resolve this with config options or is this a bug?

Thanks

**Comment by danielcondemarin** [comment]
@me4502 Can you share what your directory structure looks like? Especially where your `serverless.yml` and `next.config` files are located.

**Comment by me4502** [comment]
So there's an apps folder, which contains the nextJS project folder.

So, /apps/nextjs/

Inside nextjs is where the serverless.yml and next.config.js files are

**Comment by danielcondemarin** [comment]
Is any other directory in the full path named `static`? apart from `.next/static`

**Comment by me4502** [comment]
None named static specifically, however one contains the word static, it's called `static-website`

**Comment by danielcondemarin** [comment]
@me4502 Could you try using `2.0.3-alpha.0`? Just published a fix for this.

**Comment by me4502** [comment]
That appears to have fixed this specific issue, but now I'l getting 
```
Unable to import module 'sls-next-build/embed': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/sls-next-build/embed.js:3:26)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
```
in the CloudWatch logs, and an Internal Server Error when I navigate to the endpoints

**Comment by danielcondemarin** [comment]
Sounds like you should be able to install `next-aws-lambda` at the leaf package rather than the monorepo’s root. 

Closing this particular issue as is now solved.
