### ISSUE TITLE
Upload static to S3 and have assetPrefix to Cloudfront

### ISSUE THREAD

**Issue by JoeDevGeeeee** [danielcondemarin/serverless-nextjs-plugin#90]
Can we configure upload static to S3 but have next.js assetPrefix to point to Cloudfront
For example, currently I have this config in my `next.config.js`
```
{
    assetPrefix: "https://my-s3-bucket.s3.amazonaws.com
}
```
This way, serverless will upload my static content to my s3 bucker.
But What if I want next.js to serve my static content using cloudfront instead of s3?
I tried to set the s3 bucket name in my serverless-nextjs config like below
```
custom:
   serverless-nextjs:
       assetsBucketName: my-s3-bucket
```
But above config doesn't work, maybe because the new aws s3 url pattern? 
`htttps://my-s3-bucket.s3.amazonaws.com` V.S. `https://s3.amazonaws.com/my-s3-bucket`

Proposal: Use serverless.yml to define upload so that next.js can have assetPrefix to CDN

**Comment by danielcondemarin** [comment]
That's what `assetsBucketName` was designed for. What issue / error are you seeing?

**Comment by JoeDevGeeeee** [comment]
@danielcondemarin oh it's my configuration in serverless.yml no correct. You are right. Closing this issue, Thanks for the rapid reply
