### ISSUE TITLE
Cookie support?

### ISSUE THREAD

**Issue by stan-sack** [danielcondemarin/serverless-nextjs-plugin#94]
Hey, My cookies don't seem to be passed to my lambda functions. I think I need to add the header mapping as suggested [here](https://stackoverflow.com/questions/35572887/using-aws-gateway-api-can-i-access-the-cookies). Is there currently a way to do this in this plugin?

**Comment by danielcondemarin** [comment]
@stan-sack The plugin uses Lambda Proxy integration behind the scene, which means you should be able to see the Cookies in `event.headers`. Can you post some code with what you're trying to do?

**Comment by stan-sack** [comment]
Im trying to read the cookies from the context in `getInitialProps()` on my page and redirect if the cookies arent there. Im using a library called `nookies` to get and set the cookies:

```
    static async getInitialProps(ctx) {
        const cookies = nookies.get(ctx)
        let authToken = cookies["auth-token"]
        if (!authToken) {
            if (ctx && ctx.res) {
                ctx.res.writeHead(302, {
                    Location: "/login"
                })
                ctx.res.end()
            } else {
                Router.replace("/login")
            }
        }
        return {}
    }
```

**Comment by danielcondemarin** [comment]
@stan-sack I can't reproduce the issue, tried this and works as expected:

```js
import { setCookie } from "nookies";

function Index(props) {
  console.log(props.headers.cookie); // logs: foo=bar

  return (
    <div className="homePage">
      <div>Welcome to next.js serverless ⚡</div>
    </div>
  );
}

Index.getInitialProps = async ctx => {
  console.log(ctx.req.headers);

  setCookie(ctx, "foo", "bar", {
    maxAge: 30 * 24 * 60 * 60,
    path: "/"
  });

  return {
    headers: ctx.req.headers
  };
};

export default Index;
```

**Comment by stan-sack** [comment]
I will continue to investigate tonight. Do you how I would enable cloudwatch logging? I'm looking at the [serverless cloudwatch docs](https://serverless.com/framework/docs/providers/aws/events/cloudwatch-event/) but because serverless-nextjs-plugin is generating the functions im not sure where to put the config.

Thanks for taking the time to look at this :). Feel free to close the issue and I'll post my findings

**Comment by stan-sack** [comment]
I've confirmed it was a cloudfront issue. thanks again!
