### ISSUE TITLE
CloudFront configuration

### ISSUE THREAD

**Issue by samuv** [danielcondemarin/serverless-nextjs-plugin#97]
Hi @danielcondemarin,

I was wondering if it is possible to override the CloudFormation configuration or reference a resource with an arn or id.
It would be great to pass the domain and certificate or other CDN related things, so I don't have to change the distribution by hand and we would have a clean cloud formation stack without drifts.

I have used the lambda@edge plugin that I think have a similar case 

https://github.com/silvermine/serverless-plugin-cloudfront-lambda-edge

What do you think about it?

**Comment by danielcondemarin** [comment]
@samuv That's been implemented now 🚀 . Should be available in `v2.2.0-alpha.0`. Check https://github.com/danielcondemarin/serverless-nextjs-plugin#serving-static-assets for more details.

**Comment by samuv** [comment]
Oh wow! This is awesome, thank you.
![meme](https://thumbs.gfycat.com/SpotlessAlertGardensnake-size_restricted.gif)
